services:
  ministry:
    container_name: ministry
    depends_on:
      - redis-cluster
      - cache-redis-1
      - cache-redis-2
      - cache-redis-3
      - application-redis-1
      - application-redis-2
      - application-redis-3
    image:
      rust:1.73
    volumes:
      - ../js/build:/tmp/build
      - ../js/static:/tmp/static
      - ../api/static:/tmp/api-static
      - .:/usr/src/ministry
    working_dir: /usr/src/ministry
    command: cargo run
    environment:
      CARGO_TARGET_DIR: /tmp/target # this one's really interesting: volume mounting is incredibly slow, which slows rust builds to a crawl, so instead rust build filespace should exist in tmpfs
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 3333
      ROCKET_PUBLIC_ADDRESS: http://localhost:3333
      USE_INSECURE_HASHES: "true"
      CACHE_REDIS_URLS: redis://:hamscramble@cache-redis-1:6888
      APPLICATION_REDIS_URLS: redis://:hamscramble@application-redis-1:6999
      ROCKET_SECRET_KEY: grPMXJszWoqdlGv1M7Y+9f0FsPhxsycGVjuQ6mfobIk=  # openssl rand -base64 32
      SCYLLA_URL: some-scylla:9042
      RUST_BACKTRACE: 1
      GROOVELET_ROOT_EMAIL: "root@gooble.email"
      GROOVELET_ROOT_AUTH_PASSWORD: "jimscrimble"
      # AWS_ACCESS_KEY_ID: <fill this in if you want to test email locally>
      # AWS_SECRET_ACCESS_KEY: <you keep it in keepass, under ses-groovelet access key
      # AWS_DEFAULT_REGION: us-west-2
    ports:
      - "3333:3333"
  some-scylla:
    container_name: some-scylla
    image: scylladb/scylla
    ports:
      -  "127.0.0.1:9042:9042"
    command: --smp 2
  some-scylla2:
    container_name: some-scylla2
    image: scylladb/scylla
    command: --smp 2 --seeds=some-scylla
  some-scylla3:
    container_name: some-scylla3
    image: scylladb/scylla
    command: --smp 2 --seeds=some-scylla
  cache-redis-1:
    image: redis/redis-stack-server
    container_name: cache-redis
    hostname: cache-redis
    environment:
      - REDIS_ARGS= --requirepass hamscramble --appendonly no --save "" --maxmemory 2140000000 --maxmemory-policy allkeys-lfu --port 6888
  application-redis-1:
    image: redis/redis-stack-server
    container_name: application-redis
    hostname: application-redis
    environment:
      - REDIS_ARGS= --requirepass hamscramble --appendonly no --save "" --maxmemory 2140000000 --maxmemory-policy noeviction --port 6999