services:
  some-scylla:
    image: scylladb/scylla
    container_name: some-scylla
    ports:
      -  "127.0.0.1:9042:9042"
    networks:
      - orchestr8
  some-scylla2:
    image: scylladb/scylla
    container_name: some-scylla2
    command: --seeds=some-scylla
    networks:
      - orchestr8
  some-scylla3:
    image: scylladb/scylla
    container_name: some-scylla3
    command: --seeds=some-scylla
    networks:
      - orchestr8
  auth-redis:
    image: redis
    container_name: auth-redis
    ports:
      -  "127.0.0.1:6032:5432"
    networks:
      - orchestr8
  cache-redis:
    image: redis
    container_name: cache-redis
    ports:
      -  "127.0.0.1:6033:5432"
    networks:
      - orchestr8
  search-redis:
    image: redis
    container_name: search-redis
    ports:
      -  "127.0.0.1:6034:5432"
    networks:
      - orchestr8
  message-redis:
    image: redis
    container_name: message-redis
    ports:
      -  "127.0.0.1:6035:5432"
    networks:
      - orchestr8
networks:
  orchestr8:
    name: orchestr8
    external: true